version: "3.9"
services:
  stress:
    container_name: stress
    image: progrium/stress
    command: --vm 5 --vm-bytes 512M --timeout 1800s
    deploy:
      resources:
        limits:
          cpus: '1'